services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: marathon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - marathon-db:/var/lib/postgresql/data
    ports:
      - 15432:5432
  cli:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/marathon?schema=public
    volumes:
      - ./models/dist:/app/models/dist
      - ./models/node_modules:/app/models/node_modules
      - ./api:/app/api
  api:
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - path: ./api/src
          action: sync
          target: /app/api/src
        - path: ./api/node_modules
          action: sync
          target: /app/api/node_modules
        - path: ./models/dist
          action: sync
          target: /app/models/dist
        - path: ./models/node_modules
          action: sync
          target: /app/models/node_modules
    depends_on:
      - db
    environment:
      - APPLICATION_SECRET=${APPLICATION_SECRET}
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/marathon?schema=public
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - ALLOWED_REDIRECT_DOMAIN=localhost
      - WEBAPP_ORIGIN=http://localhost:3000
    volumes:
      - ./models/dist:/app/models/dist
      - ./models/node_modules:/app/models/node_modules
      # - ./api/src:/app/api/src
    ports:
      - 13000:3000
volumes:
  marathon-db:
