import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import type { Metadata } from "next";
import { Noto_Sans_JP, Roboto } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { AppHeader } from "./_components/models/header";
import { Container, Paper, ThemeProvider } from "@mui/material";
import { ClientApiProvider } from "./_components/models/api";
import theme from "./theme";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

const notoSansJp = Noto_Sans_JP({
  display: "swap",
  variable: "--font-noto-sans-jp",
  preload: false,
});

export const metadata: Metadata = {
  title: "RTA Marathon Scheduler",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const apiUrl = process.env["API_URL"] || "http://localhost:3000";

  return (
    <html lang="ja">
      <body className={`${notoSansJp.variable} ${roboto.variable}`}>
        <ClientApiProvider apiUrl={apiUrl}>
          <Container maxWidth="xl">
            <AppHeader />
            <AppRouterCacheProvider>
              <ThemeProvider theme={theme}>
                <Paper
                  square
                  sx={{
                    minHeight: "calc(100svh - 64px)",
                    background: "white",
                  }}
                >
                  {children}
                </Paper>
              </ThemeProvider>
            </AppRouterCacheProvider>
          </Container>
        </ClientApiProvider>
      </body>
    </html>
  );
}
