name: Testing
on: [push]
jobs:
    models:

        runs-on: ubuntu-latest
        
        strategy:
            matrix:
                node-version: ['18.x', '20.x']
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
            - run: |
                npm ci
                npm run build
              working-directory: ${{ github.workspace }}/models
            - run: npm run test
              working-directory: ${{ github.workspace }}/models
